name: locs
channels:
  - pytorch3d
  - pyg
  - iopath
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py39h7f8727e_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - aom=3.2.0=h9c3ff4c_2
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py39h06a4308_0
  - brotlipy=0.7.0=py39h3811e60_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2021.10.8=py39h06a4308_2
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - click=8.0.3=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - ffmpeg=4.4.1=h6987444_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py39h7f8727e_0
  - fvcore=0.1.5.post20211023=pyhd8ed1ab_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.1=py_2
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - grpcio=1.43.0=py39h336bf08_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.10.0=py39hf3d152e_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py39
  - jbig=2.1=hdba287a_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.2=py39h1a9c180_1
  - kornia=0.6.2=pyhd8ed1ab_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.109=h7f98852_0
  - libffi=3.4.2=h295c915_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - libnsl=2.0.0=h7f98852_0
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.19.3=h780b84a_0
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.18.0=h7f98852_0
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libva=2.13.0=h7f98852_1
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.2.1=h3452ae3_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py39h98787fa_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=5.2.0=py39h7f8727e_2
  - ncurses=6.2=h58526e2_4
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd8ed1ab_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py39hde0f152_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.3.1=pyhd8ed1ab_0
  - portalocker=2.3.2=py39hf3d152e_1
  - protobuf=3.19.3=py39he80948d_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyg=2.0.3=py39_torch_1.10.0_cu102
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.9=h543edf9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-louvain=0.15=pyhd3deb0d_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-cluster=1.5.9=py39_torch_1.10.0_cu102
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py39_torch_1.10.0_cu102
  - pytorch-sparse=0.6.12=py39_torch_1.10.0_cu102
  - pytorch-spline-conv=1.2.1=py39_torch_1.10.0_cu102
  - pytorch3d=0.6.1=py39_cu102_pyt1100
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39h3811e60_3
  - readline=8.1.2=h7f8727e_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.8=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py39h51133e4_0
  - scipy=1.7.3=py39hc147768_0
  - setuptools=59.5.0=py39hf3d152e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - svt-av1=0.8.7=h9c3ff4c_1
  - tabulate=0.8.9=py39h06a4308_0
  - tensorboard=2.6.0=py_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - termcolor=1.1.0=py39h06a4308_1
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.0=py39_cu102
  - torchvision=0.11.1=py39_cu102
  - tornado=6.1=py39h3811e60_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=4.0.1=hd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h4bd325d_1
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39h3811e60_1
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.1=ha95c52a_0
